failure-run

diff --git a/.github/workflows/w3.yaml b/.github/workflows/w3.yaml
--- a/.github/workflows/w3.yaml
+++ b/.github/workflows/w3.yaml
@@ -17,23 +17,7 @@ jobs:
          run: echo "step 2 run"
        - name: step3
          run: echo "step 3 run"
-  full_test:
-     runs-on: ubuntu-latest
-     needs: [ build, build2 ]
-     steps:
-       - name: step1
-         run: |
-           echo "test step 1"
-           sleep 10    
-  notification:
-     runs-on: ubuntu-latest
-     needs: build
-     if: ${{ needs.build.result == 'failure' || failure() }}
-     steps:
-       - name: notify
-         run: |
-           echo "Build step got failed"
-           sleep 10
+
   build2:
      runs-on: ubuntu-latest
      steps:
@@ -49,15 +33,33 @@ jobs:
        - name: step1
          run: |
            echo "test step 1"
-           sleep 10    
-  deploy:
+           sleep 10
+
+  full_test:
      runs-on: ubuntu-latest
+     needs: [ build, build2 ]
      if: ${{ always () }}
      steps:
        - name: step1
          run: |
            echo "test step 1"
+           sleep 10    
+  deploy:
+     runs-on: ubuntu-latest
+     steps:
+       - name: step1
+         run: |
+           echo "test step 1"
            sleep 10
-     needs: test
+     needs: full_test
 
+  notification:
+     runs-on: ubuntu-latest
+     needs: build
+     if: ${{ needs.build.result == 'failure' || failure() }}
+     steps:
+       - name: notify
+         run: |
+           echo "Build step got failed"
+           sleep 10
           
